apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerwebapideployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DockerWebApi
  template:
    metadata:
      labels:
        app: DockerWebApi
    spec:
      containers:
      - name: dockersamplerepos
        image: mysampleapicr.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: dockerwebapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DockerWebApi